name = "short-url-next"
compatibility_date = "2025-12-21"
compatibility_flags = ["nodejs_compat"] # Next.js éœ€è¦ Node.js å…¼å®¹å±‚
pages_build_output_dir = "public" # ğŸ‘ˆ æŒ‡å‘é€‚é…å™¨ç”Ÿæˆçš„ç›®å½•